logging:
  level:
    picker.picker_backend: debug
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.jdbc.datasource.init.DataSourceInitializer: DEBUG


spring:
  application:
    name: picker-backend

  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3307/picker_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: picker
    password: picker
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:mapper/test/schema.sql


  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# post 설정

post:
  kafka:
    topic:
      post: ${POST_KAFKA_TOPIC_POST:post-events}
      postdlq: ${POST_KAFKA_TOPIC_POSTDLQ:post-dlq}
      reply: ${POST_KAFKA_TOPIC_REPLY:reply-events}
      replydlq: ${POST_KAFKA_TOPIC_REPLYDLQ:reply-dlq}
      likes: ${POST_KAFKA_TOPIC_LIKES:likes-events}
      likesdlq: ${POST_KAFKA_TOPIC_LIKESDLQ:likes-dlq}
    groupId: ${POST_KAFKA_GROUPID:post-group}
  popularity:
    weights:
      todayviews: 1.0
      totalviews: 0.5
      comments: 0.7
      likes: 0.9
    decaytimeunit: 45000.0
